import "server-only";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/require-admin";
import { applicationIdSchema } from "@/lib/applications/application-validation";
import { requireAccountType } from "@/lib/profiles/get-current-profile";
import type { CandidateProfile, JobApplication, JobApplicationStatus, JobApplicationStatusHistory, Profile } from "@/lib/supabase/database.types";
import { createClient } from "@/lib/supabase/server";
import type { ApplicationVacancy } from "@/lib/applications/candidate-applications";
const appCols="id, vacancy_id, candidate_user_id, candidate_document_id, cover_note, status, submitted_at, withdrawn_at, created_at, updated_at";const vacancyCols="id, slug, job_title, organisation_name, employment_type, workplace_type, job_location, status, applications_open, closes_at, employer_user_id";const historyCols="id, application_id, previous_status, new_status, changed_by_user_id, change_source, public_note, created_at";
export type ReviewItem={application:JobApplication;vacancy:ApplicationVacancy;candidate:{full_name:string;professional_title:string|null;current_location:string|null;professional_summary:string|null;preferred_roles:string[]|null}};
async function hydrate(applications:JobApplication[],employerId?:string){const supabase=await createClient();const vacancyIds=[...new Set(applications.map(a=>a.vacancy_id))];const candidateIds=[...new Set(applications.map(a=>a.candidate_user_id))];const[vacancyResult,profileResult,candidateResult]=await Promise.all([vacancyIds.length?supabase.from("vacancies").select(vacancyCols).in("id",vacancyIds):Promise.resolve({data:[],error:null}),candidateIds.length?supabase.from("profiles").select("id, full_name").in("id",candidateIds):Promise.resolve({data:[],error:null}),candidateIds.length?supabase.from("candidate_profiles").select("user_id, professional_title, current_location, professional_summary, preferred_roles").in("user_id",candidateIds):Promise.resolve({data:[],error:null})]);const vacancies=((vacancyResult.data??[])as Array<ApplicationVacancy&{employer_user_id:string|null}>).filter(v=>!employerId||v.employer_user_id===employerId);const vMap=new Map(vacancies.map(v=>[v.id,v]));const pMap=new Map(((profileResult.data??[])as Pick<Profile,"id"|"full_name">[]).map(p=>[p.id,p]));const cMap=new Map(((candidateResult.data??[])as Pick<CandidateProfile,"user_id"|"professional_title"|"current_location"|"professional_summary"|"preferred_roles">[]).map(c=>[c.user_id,c]));return applications.flatMap(application=>{const vacancy=vMap.get(application.vacancy_id),profile=pMap.get(application.candidate_user_id),candidate=cMap.get(application.candidate_user_id);return vacancy&&profile?[{application,vacancy,candidate:{full_name:profile.full_name,professional_title:candidate?.professional_title??null,current_location:candidate?.current_location??null,professional_summary:candidate?.professional_summary??null,preferred_roles:candidate?.preferred_roles??null}}]:[]});}
export async function getAdminApplications(status:JobApplicationStatus|null){const access=await requireAdmin("/admin/applications");if(access.status!=="ready")return{status:access.status,items:[]}as const;const supabase=await createClient();let query=supabase.from("job_applications").select(appCols,{count:"exact"}).order("submitted_at",{ascending:false}).limit(50);if(status)query=query.eq("status",status);const{data,error}=await query;return{status:error?"error":"ready",items:error?[]:await hydrate(data as JobApplication[])}as const;}
export async function getAdminApplication(id:string){const access=await requireAdmin(`/admin/applications/${id}`);if(access.status!=="ready")return{status:access.status}as const;if(!applicationIdSchema.safeParse(id).success)notFound();const supabase=await createClient();const{data}=await supabase.from("job_applications").select(appCols).eq("id",id).maybeSingle();if(!data)notFound();const items=await hydrate([data as JobApplication]);if(!items[0])notFound();const history=await supabase.from("job_application_status_history").select(historyCols).eq("application_id",id).order("created_at",{ascending:true}).limit(100);return{status:"ready",item:items[0],history:(history.data??[])as JobApplicationStatusHistory[]}as const;}
export async function getEmployerApplications(status:JobApplicationStatus|null){const current=await requireAccountType("employer","/account/employer/applications");const supabase=await createClient();const owned=await supabase.from("vacancies").select("id").eq("employer_user_id",current.user.id).limit(100);if(owned.error)return{items:[],unavailable:true};const ids=(owned.data??[]).map(v=>v.id);if(!ids.length)return{items:[],unavailable:false};let query=supabase.from("job_applications").select(appCols).in("vacancy_id",ids).order("submitted_at",{ascending:false}).limit(50);if(status)query=query.eq("status",status);const{data,error}=await query;return{items:error?[]:await hydrate(data as JobApplication[],current.user.id),unavailable:Boolean(error)};}
export async function getEmployerApplication(id:string){const current=await requireAccountType("employer",`/account/employer/applications/${id}`);if(!applicationIdSchema.safeParse(id).success)notFound();const supabase=await createClient();const{data}=await supabase.from("job_applications").select(appCols).eq("id",id).maybeSingle();if(!data)notFound();const items=await hydrate([data as JobApplication],current.user.id);if(!items[0])notFound();const history=await supabase.from("job_application_status_history").select(historyCols).eq("application_id",id).order("created_at",{ascending:true}).limit(100);return{item:items[0],history:(history.data??[])as JobApplicationStatusHistory[]};}
