import type { Metadata } from "next";
import { AccountCard, AccountPage } from "@/components/account/account-page";
import { CvDocumentCard } from "@/components/account/documents/cv-document-card";
import { CvUploadForm } from "@/components/account/documents/cv-upload-form";
import { DocumentStatus } from "@/components/account/documents/document-status";
import { getCurrentCv } from "@/lib/documents/get-current-cv";
import { requireAccountType } from "@/lib/profiles/get-current-profile";
export const metadata: Metadata = { title: "Documents | Talvanta Africa Account", robots: { index: false, follow: false } };
export default async function Page({ searchParams }: { searchParams: Promise<{ error?: string; status?: string }> }) { const current = await requireAccountType("candidate", "/account/candidate/documents"); const document = await getCurrentCv(current.user.id); const params = await searchParams; return <AccountPage eyebrow="Candidate Account" title="Your Documents" intro="Upload and manage the current CV associated with your Talvanta Africa candidate account."><div className="grid gap-6">{params.error === "download_failed" ? <DocumentStatus status="error" message="We could not prepare this CV for download. Please try again." /> : null}{params.status === "deleted" ? <DocumentStatus status="success" message="Your CV has been deleted." /> : null}<AccountCard title={document ? "Current CV" : "No CV has been uploaded"}>{document ? <CvDocumentCard document={document} /> : <p className="leading-7 text-slate">Upload a current PDF CV to support your candidate profile.</p>}</AccountCard><AccountCard title={document ? "Replace CV" : "Upload Your CV"}><CvUploadForm replacing={Boolean(document)} /></AccountCard><AccountCard title="Document security"><div className="space-y-3 leading-7 text-slate"><p>Your CV is stored in a private document area and is not available through a public file URL. Access remains subject to authenticated permissions.</p><p>Uploaded documents are validated for supported format and size. Automated malware scanning is not currently active.</p></div></AccountCard></div></AccountPage>; }
