import { AccountCard } from "@/components/account/account-page";
import { ButtonLink } from "@/components/ui/button";
import type { CandidateDashboardData } from "@/lib/candidates/get-candidate-dashboard";
import type { CandidateProfile } from "@/lib/supabase/database.types";

const display = (value: string | number | null | undefined) => value === null || value === undefined || value === "" ? "Not provided" : String(value);
const date = (value: string) => { const parsed = new Date(value); return Number.isNaN(parsed.valueOf()) ? "Date unavailable" : new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeZone: "Africa/Lagos" }).format(parsed); };
function safeUrl(value: string | null) { if (!value) return null; try { const url = new URL(value); return url.protocol === "https:" ? url.toString() : null; } catch { return null; } }
function ExternalLink({ value, label }: { value: string | null; label: string }) { const href = safeUrl(value); return href ? <a className="break-all font-bold text-green underline" href={href} target="_blank" rel="noreferrer">{label}<span className="sr-only"> (opens in a new tab)</span></a> : <>Not provided</>; }
function Tags({ values }: { values: string[] | null }) { return values?.length ? <ul className="flex flex-wrap gap-2">{values.map((value) => <li key={value} className="rounded-full border border-border-grey bg-soft-grey px-3 py-1 text-sm text-navy">{value}</li>)}</ul> : <p className="text-slate">No preferences added yet</p>; }
function Detail({ term, children }: { term: string; children: React.ReactNode }) { return <div className="min-w-0"><dt className="font-bold text-navy">{term}</dt><dd className="mt-1 whitespace-pre-wrap break-words leading-7 text-slate">{children}</dd></div>; }

export function DashboardProfileAndPreferences({ candidate }: { candidate: CandidateProfile | null }) { return <div className="grid gap-6 lg:grid-cols-2"><AccountCard title="Professional Profile">{candidate ? <dl className="grid gap-4 sm:grid-cols-2"><Detail term="Professional title">{display(candidate.professional_title)}</Detail><Detail term="Current location">{display(candidate.current_location)}</Detail><Detail term="Relevant experience">{candidate.years_of_experience === null ? "Not provided" : `${candidate.years_of_experience} years`}</Detail><Detail term="Phone number">{display(candidate.phone)}</Detail><Detail term="Professional summary">{display(candidate.professional_summary)}</Detail><Detail term="LinkedIn"><ExternalLink value={candidate.linkedin_url} label="View LinkedIn profile" /></Detail><Detail term="Portfolio"><ExternalLink value={candidate.portfolio_url} label="View professional portfolio" /></Detail></dl> : <p className="text-slate">We could not load your candidate profile at this time.</p>}<div className="mt-5 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/account/candidate/profile">View Full Profile</ButtonLink><ButtonLink href="/account/candidate/profile/edit" variant="outline">Edit Profile</ButtonLink></div></AccountCard><AccountCard title="Career Preferences"><div className="space-y-5"><div><h3 className="font-bold text-navy">Preferred roles</h3><div className="mt-2"><Tags values={candidate?.preferred_roles ?? null} /></div></div><div><h3 className="font-bold text-navy">Preferred locations</h3><div className="mt-2"><Tags values={candidate?.preferred_locations ?? null} /></div></div><div><h3 className="font-bold text-navy">Employment types</h3><div className="mt-2"><Tags values={candidate?.preferred_employment_types ?? null} /></div></div><div><h3 className="font-bold text-navy">Workplace types</h3><div className="mt-2"><Tags values={candidate?.preferred_workplace_types ?? null} /></div></div></div><p className="mt-5 text-sm leading-6 text-slate">These preferences help organise your candidate profile.</p><ButtonLink className="mt-4" href="/account/candidate/profile/edit" variant="outline">Update Career Preferences</ButtonLink></AccountCard></div>; }

export function DashboardActivityAndActions({ data }: { data: CandidateDashboardData }) { const items = [["Account created", data.current.profile.created_at], ["Profile last updated", data.candidate?.updated_at ?? data.current.profile.updated_at], ...(data.cv ? [["CV uploaded or updated", data.cv.updated_at]] : []), ...(data.current.user.email_confirmed_at ? [["Email verified", data.current.user.email_confirmed_at]] : [])] as [string, string][]; const actions = [["Edit Professional Profile", "/account/candidate/profile/edit"], ["Manage CV", "/account/candidate/documents"], ["View Career Opportunities", "/jobs"], ["Read Candidate Support", "/job-seekers"], ["Contact Talvanta Africa", "/contact"]] as const; return <div className="grid gap-6 lg:grid-cols-2"><AccountCard title="Recent Account Information"><dl className="space-y-4">{items.map(([label, value]) => <div key={label} className="flex flex-wrap justify-between gap-2 border-b border-border-grey pb-3 last:border-0 last:pb-0"><dt className="font-bold text-navy">{label}</dt><dd className="text-slate">{date(value)}</dd></div>)}</dl><p className="mt-4 text-sm text-slate">This summary uses existing account timestamps and is not a complete activity or audit log.</p></AccountCard><AccountCard title="Quick Actions"><ul className="grid gap-3 sm:grid-cols-2">{actions.map(([label, href]) => <li key={href}><ButtonLink className="w-full" href={href} variant="outline">{label}</ButtonLink></li>)}</ul></AccountCard></div>; }

export function CandidateFullProfile({ data }: { data: CandidateDashboardData }) { const candidate = data.candidate; if (!candidate) return <AccountCard><p role="alert" className="leading-7 text-slate">{data.candidateUnavailable ? "We could not load your candidate profile at this time." : "Your candidate profile information is unavailable."}</p><div className="mt-5 flex gap-3"><ButtonLink href="/account">Account</ButtonLink><ButtonLink href="/contact" variant="outline">Contact Support</ButtonLink></div></AccountCard>; return <div className="grid gap-6"><AccountCard title="Personal and Contact Information"><dl className="grid gap-5 sm:grid-cols-2"><Detail term="Full name">{data.current.profile.full_name}</Detail><Detail term="Account email">{data.current.user.email ?? "Email unavailable"}</Detail><Detail term="Phone number">{display(candidate.phone)}</Detail><Detail term="Current location">{display(candidate.current_location)}</Detail></dl></AccountCard><AccountCard title="Professional Overview"><dl className="grid gap-5 sm:grid-cols-2"><Detail term="Professional title">{display(candidate.professional_title)}</Detail><Detail term="Years of relevant experience">{candidate.years_of_experience === null ? "Not provided" : `${candidate.years_of_experience} years`}</Detail><Detail term="Professional summary">{display(candidate.professional_summary)}</Detail></dl></AccountCard><AccountCard title="Career Preferences"><div className="grid gap-5 sm:grid-cols-2"><div><h3 className="font-bold text-navy">Preferred roles</h3><div className="mt-2"><Tags values={candidate.preferred_roles} /></div></div><div><h3 className="font-bold text-navy">Preferred locations</h3><div className="mt-2"><Tags values={candidate.preferred_locations} /></div></div><div><h3 className="font-bold text-navy">Employment types</h3><div className="mt-2"><Tags values={candidate.preferred_employment_types} /></div></div><div><h3 className="font-bold text-navy">Workplace types</h3><div className="mt-2"><Tags values={candidate.preferred_workplace_types} /></div></div></div></AccountCard><AccountCard title="External Professional Links"><dl className="grid gap-5 sm:grid-cols-2"><Detail term="LinkedIn"><ExternalLink value={candidate.linkedin_url} label="View LinkedIn profile" /></Detail><Detail term="Portfolio"><ExternalLink value={candidate.portfolio_url} label="View professional portfolio" /></Detail></dl></AccountCard><div className="flex flex-col gap-3 sm:flex-row"><ButtonLink href="/account/candidate/profile/edit">Edit Profile</ButtonLink><ButtonLink href="/account/candidate/documents" variant="outline">Manage CV</ButtonLink></div></div>; }
