import Link from "next/link";
import { AccountCard } from "@/components/account/account-page";
import { ButtonLink } from "@/components/ui/button";
import { formatFileSize } from "@/lib/documents/cv-validation";
import { candidateCompletion, nextCandidateProfileStep } from "@/lib/profiles/profile-completion";
import type { CandidateDashboardData } from "@/lib/candidates/get-candidate-dashboard";

const date = (value: string) => { const parsed = new Date(value); return Number.isNaN(parsed.valueOf()) ? "Date unavailable" : new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeZone: "Africa/Lagos" }).format(parsed); };
export function CandidateDashboardCards({ data }: { data: CandidateDashboardData }) { const completion = candidateCompletion(data.current.profile, data.candidate); const confirmed = Boolean(data.current.user.email_confirmed_at); return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><AccountCard title="Profile Completion"><p className="text-3xl font-extrabold text-navy">{completion}%</p><div className="mt-3 h-3 overflow-hidden rounded-full bg-border-grey" role="progressbar" aria-label="Profile Completion" aria-valuemin={0} aria-valuemax={100} aria-valuenow={completion}><div className="h-full bg-green" style={{ width: `${completion}%` }} /></div><p className="mt-3 text-sm leading-6 text-slate">Next step: {nextCandidateProfileStep(data.current.profile, data.candidate)}. This is profile guidance, not a candidate score.</p><ButtonLink className="mt-4 w-full" href="/account/candidate/profile/edit" variant="outline">{completion < 100 ? "Complete Your Profile" : "Review Your Profile"}</ButtonLink></AccountCard><AccountCard title="CV Status">{data.cvUnavailable ? <p className="text-slate">Your CV information could not be loaded at this time.</p> : data.cv ? <><p className="font-bold text-navy">Current CV uploaded</p><p className="mt-2 break-all text-sm text-slate">{data.cv.original_filename}</p><p className="mt-1 text-sm text-slate">{formatFileSize(data.cv.file_size_bytes)} · Uploaded {date(data.cv.uploaded_at)}</p></> : <p className="text-slate">No CV uploaded</p>}<ButtonLink className="mt-4 w-full" href="/account/candidate/documents" variant="outline">{data.cv ? "Manage CV" : "Upload Your CV"}</ButtonLink></AccountCard><AccountCard title="Account Status"><ul className="space-y-2 text-slate"><li>{confirmed ? "Email verified" : "Email verification required"}</li>{data.current.profile.onboarding_completed ? <li>Candidate profile active</li> : null}</ul>{!confirmed ? <Link className="mt-4 inline-flex min-h-11 items-center font-bold text-green underline" href="/verify-email">Review Verification Guidance</Link> : null}</AccountCard><AccountCard title="Career Opportunities"><p className="leading-7 text-slate">Review verified opportunities published through Talvanta Africa.</p><ButtonLink className="mt-4 w-full" href="/jobs" variant="outline">View Career Opportunities</ButtonLink></AccountCard></div>; }
