import Link from "next/link";
import { ButtonLink } from "@/components/ui/button";
import type { CandidateProfile, EmployerProfile, Profile } from "@/lib/supabase/database.types";

const display = (value: string | number | null | undefined) => value === null || value === undefined || value === "" ? "Not provided" : String(value);
const list = (values: string[] | null) => values?.length ? values.join(", ") : "Not provided";
function validHttpsUrl(value: string | null) { if (!value) return null; try { const url = new URL(value); return url.protocol === "https:" ? url.toString() : null; } catch { return null; } }
function SafeUrl({ value, label }: { value: string | null; label: string }) { const href = validHttpsUrl(value); return href ? <a className="break-all font-bold text-green underline" href={href} target="_blank" rel="noreferrer">{label}<span className="sr-only"> (opens in a new tab)</span></a> : <>Not provided</>; }
function Rows({ items }: { items: readonly [string, React.ReactNode][] }) { return <dl className="grid gap-5 sm:grid-cols-2">{items.map(([label, content]) => <div key={label} className="min-w-0"><dt className="font-bold text-navy">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words leading-7 text-slate">{content}</dd></div>)}</dl>; }

export function CandidateDetails({ profile, details, email }: { profile: Profile; details: CandidateProfile; email: string }) { return <><Rows items={[["Full name", profile.full_name], ["Email", email], ["Phone", display(details.phone)], ["Current location", display(details.current_location)], ["Professional title", display(details.professional_title)], ["Years of experience", display(details.years_of_experience)], ["Professional summary", display(details.professional_summary)], ["LinkedIn profile", <SafeUrl key="linkedin" value={details.linkedin_url} label="View LinkedIn profile" />], ["Portfolio", <SafeUrl key="portfolio" value={details.portfolio_url} label="View portfolio" />], ["Preferred roles", list(details.preferred_roles)], ["Preferred locations", list(details.preferred_locations)], ["Employment preferences", list(details.preferred_employment_types)], ["Workplace preferences", list(details.preferred_workplace_types)]]} /><ButtonLink className="mt-6" href="/account/candidate/edit">Edit Profile</ButtonLink></>; }
export function EmployerDetails({ profile, details, email }: { profile: Profile; details: EmployerProfile; email: string }) { return <><Rows items={[["Full name", profile.full_name], ["Email", email], ["Organisation name", display(details.organisation_name)], ["Organisation website", <SafeUrl key="website" value={details.organisation_website} label="Visit organisation website" />], ["Industry", display(details.industry)], ["Organisation size", display(details.organisation_size)], ["Contact role", display(details.contact_role)], ["Phone", display(details.phone)], ["Organisation location", display(details.organisation_location)], ["Organisation summary", display(details.organisation_summary)]]} /><ButtonLink className="mt-6" href="/account/employer/edit">Edit Profile</ButtonLink></>; }
export function MissingRoleProfile() { return <div role="alert"><p className="leading-7 text-slate">We could not load the role profile associated with this account. Please contact support before continuing.</p><Link className="mt-4 inline-flex min-h-11 items-center font-bold text-green underline" href="/contact">Contact Support</Link></div>; }
