import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { submitApplication } from "@/app/jobs/[slug]/apply/actions";
import { ApplicationForm } from "@/components/applications/application-form";
import { AccountCard, AccountPage } from "@/components/account/account-page";
import { ButtonLink } from "@/components/ui/button";
import { getCandidateProfileSummary, requireCandidateApplications } from "@/lib/applications/candidate-applications";
import { getCurrentCv } from "@/lib/documents/get-current-cv";
import { getPublicVacancy } from "@/lib/jobs";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const vacancy=await getPublicVacancy(slug);return{title:vacancy?`Apply for ${vacancy.job_title} | Talvanta Africa`:"Apply | Talvanta Africa",robots:{index:false,follow:false}}}
export default async function Page({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{submitted?:string;existing?:string}>}){const{slug}=await params;const query=await searchParams;const current=await requireCandidateApplications(`/jobs/${slug}/apply`);const vacancy=await getPublicVacancy(slug);if(!vacancy||!vacancy.applications_open)notFound();
  if(query.submitted)return <AccountPage eyebrow="Candidate Application" title="Application Submitted" intro="Your application has been recorded successfully. Submission does not guarantee shortlisting, an interview, an offer, or employment."><div className="flex flex-wrap gap-3"><ButtonLink href={`/account/candidate/applications/${query.submitted}`}>View Application</ButtonLink><ButtonLink href="/account/candidate/applications" variant="outline">View All Applications</ButtonLink><ButtonLink href="/jobs" variant="outline">Return to Jobs</ButtonLink></div></AccountPage>;
  if(query.existing)return <AccountPage eyebrow="Candidate Application" title="Application Already Submitted" intro="You have already submitted an application for this opportunity."><ButtonLink href={`/account/candidate/applications/${query.existing}`}>View Your Application</ButtonLink></AccountPage>;
  const[profile,cv]=await Promise.all([getCandidateProfileSummary(current.user.id),getCurrentCv(current.user.id)]);return <AccountPage eyebrow="Candidate Application" title={`Apply for ${vacancy.job_title}`} intro={`${vacancy.organisation_name} · ${vacancy.job_location} · ${vacancy.employment_type}`}><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.65fr)]"><AccountCard title="Application"><ApplicationForm action={submitApplication.bind(null,slug)} cv={cv?{id:cv.id,original_filename:cv.original_filename}:null}/></AccountCard><div className="grid content-start gap-6"><AccountCard title="Candidate profile"><dl className="grid gap-3"><div><dt className="font-bold text-navy">Name</dt><dd className="text-slate">{current.profile.full_name}</dd></div><div><dt className="font-bold text-navy">Professional title</dt><dd className="text-slate">{profile?.professional_title??"Not provided"}</dd></div><div><dt className="font-bold text-navy">Location</dt><dd className="text-slate">{profile?.current_location??"Not provided"}</dd></div></dl></AccountCard><AccountCard title="CV">{cv?<p className="break-all text-slate">Current CV available: {cv.original_filename}</p>:<><p className="text-slate">No CV is currently associated with your candidate account.</p><ButtonLink className="mt-4" href="/account/candidate/documents" variant="outline">Upload Your CV</ButtonLink></>}</AccountCard></div></div></AccountPage>}
