import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { AccountCard, AccountPage } from "@/components/account/account-page";
import { CandidateNavigation } from "@/components/account/candidate-navigation";
import { SignOutButton } from "@/components/auth/sign-out-button";
import { ButtonLink } from "@/components/ui/button";
import { requireAccountType } from "@/lib/profiles/get-current-profile";
export const metadata: Metadata = { title: "Account Settings | Talvanta Africa", robots: { index: false, follow: false } };
export default async function Page() { const current = await requireAccountType("candidate", "/account/settings"); if (!current.profile.onboarding_completed) redirect("/account/onboarding/candidate"); return <><CandidateNavigation /><AccountPage eyebrow="Candidate Account" title="Account Settings" intro="Review your account information and access security, privacy, and support options."><div className="grid gap-6 lg:grid-cols-2"><AccountCard title="Account Information"><dl className="space-y-4"><div><dt className="font-bold text-navy">Email address</dt><dd className="mt-1 break-all text-slate">{current.user.email ?? "Email unavailable"}</dd></div><div><dt className="font-bold text-navy">Account type</dt><dd className="mt-1 text-slate">Candidate</dd></div></dl><p className="mt-4 text-sm leading-6 text-slate">Email changes and account-type changes are not available in this release.</p></AccountCard><AccountCard title="Security"><p className="leading-7 text-slate">Use the password-recovery flow if you need to replace your current password.</p><div className="mt-5 flex flex-col items-stretch gap-3 sm:flex-row sm:items-center"><ButtonLink href="/forgot-password">Reset Your Password</ButtonLink><SignOutButton /></div></AccountCard><AccountCard title="Privacy and Terms"><ul className="space-y-2"><li><Link className="inline-flex min-h-11 items-center font-bold text-green underline" href="/privacy">Privacy Information</Link></li><li><Link className="inline-flex min-h-11 items-center font-bold text-green underline" href="/terms">Terms of Use</Link></li></ul></AccountCard><AccountCard title="Support"><p className="leading-7 text-slate">Contact Talvanta Africa if you need help with your authenticated account.</p><ButtonLink className="mt-5" href="/contact" variant="outline">Contact Support</ButtonLink></AccountCard></div></AccountPage></>; }
