import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { recoverProfile } from "@/app/account/actions";
import { AccountCard, AccountPage } from "@/components/account/account-page";
import { Button, ButtonLink } from "@/components/ui/button";
import { getCurrentProfile } from "@/lib/profiles/get-current-profile";
export const metadata: Metadata = { title: "Your Account | Talvanta Africa", description: "Access your authenticated Talvanta Africa account.", robots: { index: false, follow: false } };
export default async function Page() { const current = await getCurrentProfile(); if (current.status === "unauthenticated") redirect("/sign-in?next=/account"); if (current.status === "ready") redirect(current.profile.onboarding_completed ? `/account/${current.profile.account_type}` : `/account/onboarding/${current.profile.account_type}`); const permission = current.status === "forbidden"; return <AccountPage eyebrow="Account" title={permission ? "Account access unavailable" : "Complete account setup"} intro={permission ? "You do not have permission to access this account information." : "We could not find a complete database profile for this authenticated account."}><AccountCard><p className="leading-7 text-slate">{current.status === "missing" ? "You may try the controlled recovery below. It uses only your authenticated identity and approved signup metadata." : "The account type is missing or unsupported, or the profile service is temporarily unavailable. Please contact Talvanta Africa for support."}</p>{current.status === "missing" ? <form action={recoverProfile} className="mt-5"><Button type="submit">Recover Account Setup</Button></form> : <ButtonLink className="mt-5" href="/contact">Contact Support</ButtonLink>}<p className="mt-4 text-sm"><Link className="font-bold text-green underline" href="/">Return to the public website</Link></p></AccountCard></AccountPage>; }
